// Fixed content shared by several demos. Kept here rather than inside a demo definition
// because three of them need the same long document: caching needs it to clear the
// implicit-cache minimum, RAG needs it to be worth retrieving from, and compression needs
// a history long enough that summarizing it is a real saving.

// Long enough that stuffing it whole is visibly expensive. Gemini's implicit cache needs
// roughly 2,000+ tokens before it will consider a prefix worth keeping.
export const DOC_CHUNKS = [
  'COST ENGINEERING FOR LARGE LANGUAGE MODELS — INTERNAL HANDBOOK',
  [
    'SECTION 1. THE BILLING MODEL',
    '',
    'Every request to a large language model is billed in tokens, not in words, characters, or',
    'requests. A token is a fragment of text produced by the tokenizer: common words are usually',
    'a single token, rare words are broken into several pieces, and digits are almost always',
    'billed one token per digit. The cost of a request is therefore only loosely related to how',
    'long it looks to a human reader.',
    '',
    'Requests are billed in two separate directions. Input tokens cover everything sent to the',
    'model: the system instruction, the conversation history, any retrieved documents, and the',
    "user's actual question. Output tokens cover what the model generates in reply. These are",
    'priced differently, and output is consistently the more expensive of the two, because',
    'generating text is a sequential process while reading it is a parallel one.',
  ].join('\n'),
  [
    'SECTION 2. WHY OUTPUT COSTS MORE THAN INPUT',
    '',
    'When a model reads a prompt, it processes the entire sequence in one parallel pass. The',
    'hardware is used efficiently and the work scales well. When a model writes a reply, it',
    'produces one token at a time, and each new token requires another pass over everything',
    'written so far. A two hundred token answer is therefore two hundred sequential steps, each',
    'one slightly more expensive than the last.',
    '',
    'This asymmetry is the single most important fact in cost engineering. It means a long prompt',
    'is cheap relative to a long answer, and that the most effective lever available to most',
    'teams is constraining response length rather than trimming the prompt.',
  ].join('\n'),
  [
    'SECTION 3. THE MULTIPLIER PROBLEM',
    '',
    'A prompt that is sent once is not worth optimizing. A prompt that is sent ten thousand times',
    'a day is a recurring line item. System instructions are the clearest example: they are',
    'usually written once, early in a project, by someone experimenting, and then resent on every',
    'single request for the lifetime of the feature. A three hundred token system prompt sent one',
    'million times is three hundred million input tokens.',
    '',
    'The practical rule is that anything appearing in every request deserves scrutiny in',
    'proportion to request volume, while anything appearing once deserves none.',
  ].join('\n'),
  [
    'SECTION 4. REASONING TOKENS',
    '',
    'Newer model families reason before answering. This reasoning is generated text, it is billed',
    'as output, and it is frequently larger than the prompt and the visible answer combined. A',
    'short question can produce thirty input tokens, two hundred fifty visible output tokens, and',
    'nine hundred reasoning tokens. The reasoning is not shown to the user, which makes it the',
    'easiest cost in the system to overlook.',
    '',
    'Reasoning can usually be reduced or disabled per request. Whether it should be depends on',
    'the task: it earns its cost on genuinely hard problems and wastes it on formatting,',
    'extraction, and classification.',
  ].join('\n'),
  [
    'SECTION 5. CACHING',
    '',
    'Providers cache prefixes of prompts they have seen recently. When a later request begins',
    'with the same content, the cached portion is billed at a reduced rate or not at all. This',
    'happens automatically on some platforms and must be requested explicitly on others.',
    '',
    'Caching rewards a specific prompt structure: stable content first, variable content last. A',
    'prompt beginning with a long fixed document and ending with a short changing question caches',
    'well. The same prompt with the question at the top does not cache at all, because the prefix',
    'differs on every request. Reordering costs nothing and can halve a bill.',
  ].join('\n'),
  [
    'SECTION 6. RETRIEVAL VERSUS STUFFING',
    '',
    'The simplest way to give a model context is to send everything and let it find what matters.',
    'This works, and it is expensive. The alternative is to retrieve only the passages likely to',
    'be relevant and send those instead. For a document of any size the difference is large,',
    'often an order of magnitude, and answer quality is frequently unchanged or better, because',
    'the model is not distracted by irrelevant material.',
    '',
    'Retrieval introduces its own infrastructure: a store, an index, and an embedding step. That',
    'cost is real but fixed, while stuffing costs scale with every single request.',
  ].join('\n'),
  [
    'SECTION 7. CONVERSATION HISTORY',
    '',
    'Chat applications resend the entire conversation on every turn, because the model has no',
    'memory between calls. A conversation that has run for forty turns sends thirty nine turns of',
    'history in order to ask its fortieth question. History is the fastest growing input cost in',
    'any conversational product.',
    '',
    'The mitigation is summarization: periodically replace old turns with a compact summary that',
    'preserves the facts the conversation depends on. This trades a small quality risk for a',
    'large and permanent reduction in per turn cost.',
  ].join('\n'),
  [
    'SECTION 8. OUTPUT SHAPE',
    '',
    'Asking for prose produces prose: transitions, hedging, restatement of the question, and a',
    'closing summary. Asking for structured output produces fields. For any task whose result is',
    'data rather than explanation, structured output is dramatically cheaper, and it is easier to',
    'consume programmatically.',
    '',
    'Explicit length limits are the blunt instrument version of the same idea. They guarantee an',
    'upper bound on cost, at the risk of truncating a reply mid sentence.',
  ].join('\n'),
  [
    'SECTION 9. MODEL SELECTION',
    '',
    'Model families are priced in tiers that differ by an order of magnitude. The most capable',
    'model is not required for most work. Classification, extraction, formatting, and routing are',
    'routinely handled by the smallest tier at a fraction of the cost, while the largest tier is',
    'reserved for the small proportion of requests that genuinely need it.',
    '',
    'Routing requests to the cheapest model that can handle them is the highest leverage change',
    'available to most systems, and it requires no change to prompts at all.',
  ].join('\n'),
  [
    'SECTION 10. MEASUREMENT',
    '',
    'None of the above can be managed without measurement. Every provider returns token usage on',
    'every response. Recording those numbers per feature, per team, and per user request is what',
    'turns an unexplained monthly invoice into a set of tractable engineering problems.',
    '',
    'Measurement is not itself an optimization. It is the precondition for all of them.',
  ].join('\n'),
  [
    'SECTION 11. BATCH PROCESSING',
    '',
    'Work that no human is waiting for does not need to be answered in seconds. Batch interfaces',
    'accept a large set of requests, process them asynchronously over a window of hours, and',
    'return the results together, at a substantial discount to interactive pricing. The tokens',
    'are identical and the model is identical; the only thing given up is immediacy.',
    '',
    'The mistake teams make is treating batch as an advanced technique to adopt later. For any',
    'workload that is genuinely offline — nightly classification, backfills, evaluation runs — it',
    'is the default, and interactive pricing is the exception that needs justifying.',
  ].join('\n'),
  [
    'SECTION 12. STREAMING AND PERCEIVED COST',
    '',
    'Streaming a response changes nothing about what is billed. The same tokens are generated and',
    'the same amount is charged. What changes is the user’s perception: first output appears in',
    'a fraction of the time, which makes a long answer feel acceptable when a silent wait of the',
    'same duration would not.',
    '',
    'This is worth stating explicitly because streaming is often filed under performance work',
    'alongside genuine cost reductions. It belongs in a different category. It buys patience,',
    'not budget.',
  ].join('\n'),
  [
    'SECTION 13. RETRIES AND FAILURE COSTS',
    '',
    'A request that fails after the model has generated its answer is billed in full. Timeouts',
    'set too aggressively, clients that retry on any error, and validation that rejects output',
    'after the fact all produce paid work that is thrown away. In a poorly configured system,',
    'retries can account for a noticeable fraction of the invoice while appearing nowhere in any',
    'feature-level accounting.',
    '',
    'Retry only on errors that are actually transient, use backoff, and cap attempts. If output',
    'is being rejected by a validator, fix the prompt rather than paying for the same generation',
    'repeatedly.',
  ].join('\n'),
  [
    'SECTION 14. FEW-SHOT EXAMPLES',
    '',
    'Examples in a prompt are among the most effective ways to control model behaviour, and among',
    'the most expensive things to leave in place unexamined. Each example is input tokens on every',
    'request. Teams routinely add a fifth, sixth and seventh example while debugging and never',
    'remove any of them once the behaviour is correct.',
    '',
    'The discipline is to treat example count as a tunable parameter: reduce it until quality',
    'degrades, then add one back. Most prompts need fewer examples than they carry.',
  ].join('\n'),
  [
    'SECTION 15. TOOL AND FUNCTION DEFINITIONS',
    '',
    'When a model is given tools, the definitions of those tools are sent with every request.',
    'A schema with twenty tools, each with a description and several typed parameters, can be',
    'larger than the conversation it accompanies. Unlike a system prompt, this cost is easy to',
    'miss because the definitions usually live in code rather than in a visible prompt string.',
    '',
    'Send only the tools plausibly relevant to the current step. Descriptions should be written',
    'for the model, which needs a sentence, rather than for a documentation site.',
  ].join('\n'),
  [
    'SECTION 16. EMBEDDINGS',
    '',
    'Embedding models are priced far below generation models, and embedding a corpus once is',
    'cheap relative to sending it repeatedly. This is the arithmetic that makes retrieval',
    'worthwhile: a fixed indexing cost replaces a recurring context cost.',
    '',
    'The cost that surprises teams is re-embedding. A change of embedding model, a change of',
    'chunking strategy, or a corpus that turns over frequently all mean paying the indexing cost',
    'again, and at corpus scale that is not a rounding error.',
  ].join('\n'),
  [
    'SECTION 17. EVALUATION',
    '',
    'Evaluation runs are model calls, and thorough evaluation is a large number of them. A suite',
    'of five hundred cases run against three prompt variants on every change is fifteen hundred',
    'requests per change. This is worth paying for, but it should be a budgeted, visible line',
    'rather than an unexplained increase attributed to production traffic.',
    '',
    'Evaluation is also the clearest candidate for batch pricing and for the smallest model that',
    'can grade the task reliably.',
  ].join('\n'),
  [
    'SECTION 18. THE ORDER TO DO THINGS IN',
    '',
    'Measure first, because nothing can be prioritized without numbers. Then route to a cheaper',
    'model, which requires no prompt changes. Then constrain output, which is the expensive half.',
    'Then trim what is resent on every request: system prompts, examples, tool definitions and',
    'history. Then restructure prompts so caching can apply. Then move offline work to batch. Then,',
    'and only then, consider retrieval infrastructure, which is the only item on this list that',
    'introduces a system to operate.',
    '',
    'Teams commonly attempt this list in reverse, beginning with a vector database and ending,',
    'months later, with the discovery that the largest single cost was a system prompt nobody had',
    'read since the prototype.',
  ].join('\n'),
];

export const REFERENCE_DOC = DOC_CHUNKS.join('\n\n');

// A question whose answer lives in exactly one section above.
export const DOC_QUESTION = 'According to the handbook, why does output cost more than input?';

// The single section that answers it — what a retrieval step would have returned.
export const DOC_SNIPPET = [
  'SECTION 2. WHY OUTPUT COSTS MORE THAN INPUT',
  '',
  'When a model reads a prompt, it processes the entire sequence in one parallel pass. The',
  'hardware is used efficiently and the work scales well. When a model writes a reply, it',
  'produces one token at a time, and each new token requires another pass over everything',
  'written so far. A two hundred token answer is therefore two hundred sequential steps, each',
  'one slightly more expensive than the last.',
].join('\n');

// A conversation long enough that resending it verbatim is a real cost.
export const CHAT_HISTORY = [
  "User: We're building an internal tool that summarizes support tickets. Where should we start?",
  'Assistant: Start by deciding what the summary is for. Triage summaries and executive summaries have different length and tone requirements, and that decision drives everything else.',
  'User: Triage. The support leads read them each morning to decide what to escalate.',
  'Assistant: Then keep them short and factual: what the customer reported, what was tried, and what is blocking. Avoid narrative. Three or four lines is usually enough for a triage decision.',
  "User: We tried that but the summaries kept including the customer's full name and account number.",
  'Assistant: That is a prompt problem rather than a model problem. Add an explicit instruction to exclude personally identifying details, and give one example of a compliant summary. Examples constrain behaviour more reliably than prohibitions do.',
  'User: Good. We also noticed the summaries get worse on long tickets, the ones with twenty or thirty replies.',
  'Assistant: Long tickets exceed what the model can attend to usefully. Summarize each reply thread in chunks, then summarize the summaries. Quality holds up much better than a single pass over the whole thing.',
  'User: How do we know if the summaries are actually any good?',
  'Assistant: Have the support leads mark a sample as useful or not useful for a week. That gives you a baseline. Automated scoring is worth adding later, but only once you know what good looks like to the people reading them.',
  'User: Makes sense. One more thing, the tool is getting expensive and finance has started asking.',
  'Assistant: Measure per ticket cost first, split into input and output tokens. For a summarization workload the input is usually dominant, because the whole ticket is being sent. That points at chunking and retrieval rather than at shortening the output.',
].join('\n');

// The same conversation, compressed to the facts the next answer actually depends on.
export const CHAT_SUMMARY = [
  'Summary of the conversation so far: The team is building an internal tool that summarizes',
  'support tickets for morning triage by support leads. Agreed: summaries should be short and',
  'factual (what was reported, what was tried, what is blocking), must exclude personally',
  'identifying details via an explicit instruction plus one worked example, and long tickets',
  'should be summarized in chunks then combined rather than in a single pass. Quality will be',
  'judged by having support leads mark a sample useful or not useful for a week before adding',
  'automated scoring. Cost has become a concern for finance, and per ticket cost should be',
  'measured split by input and output tokens.',
].join('\n');

export const CHAT_QUESTION = 'Given all of that, what should we do first this week?';
